export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	SET_LOAD_USER: 'SET_LOAD_USER',
	SET_NOTE: 'SET_NOTE',
	DELETE_NOTE: 'DELETE_NOTE',
	SET_NOTES: 'SET_NOTES',
	LOGOUT: 'LOGOUT',
	SET_TRIGGER_NEW_NOTE: 'SET_TRIGGER_NEW_NOTE',
	SET_WEATHER: 'SET_WEATHER',
};
